service: ms2-analysis-service

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  memorySize: 512

  # Permesso a tutte le funzioni di questo servizio di scrivere sul Bucket S3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
      Resource:
        - !Join ['', [!GetAtt RepositoryBucket.Arn, '/*']]

build:
  esbuild: false

plugins:
  - serverless-step-functions
  - serverless-offline

functions:
  wrapperAdapter:
    handler: src/wrapper/handler.startAnalysis
    events:
      - http:
          path: /analyze
          method: post

  # Lambda che scarica la repository
  pullRepoToS3:
    handler: dist/lambdas/pull-repo.handler
    timeout: 60
    memorySize: 1024
    environment:
      S3_BUCKET_NAME: !Ref RepositoryBucket
    layers:
      # Eseguibile di git all'ambiente
      - arn:aws:lambda:eu-central-1:553035198032:layer:git-lambda2:8

# Creazione del Bucket S3
resources:
  Resources:
    RepositoryBucket:
      Type: AWS::S3::Bucket
      Properties:
        # Nome del bucket reso univoco a livello globale (fondamentale)
        BucketName: ms2-analysis-repos-bucket-${sls:stage}-${aws:accountId}
        LifecycleConfiguration:
          Rules:
            - Id: AutoDeleteOldZips
              Status: Enabled
              ExpirationInDays: 1
