service: ms2-analysis-service

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-central-1
  memorySize: 512
  environment:
    API_KEY: ${ssm:/ms2/condivisa/api-key}
  iamRoleStatements:
    # Permesso per scrivere, leggere e CANCELLARE su S3
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
      Resource:
        - !Join ['', [!GetAtt RepositoryBucket.Arn, '/*']]
    # Permesso per il Wrapper NestJS di avviare la Step Function
    - Effect: Allow
      Action:
        - states:StartExecution
      Resource:
        - !Sub 'arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:ms2-pipeline-${sls:stage}'
    # Permesso all'Orchestratore di chiamare gli Agenti AI
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: '*'
    # Permesso a tutte le lambda di interrogare l'intelligenza artificiale
    - Effect: Allow
      Action:
        - bedrock:InvokeModel
        - bedrock:InvokeModelWithResponseStream
        - bedrock:InvokeAgent
      Resource: '*'

build:
  esbuild:
    bundle: true
    minify: true
    target: node20
    exclude:
      - '@aws-sdk/*'
    external:
      - 'class-transformer/storage'
      - repomix
      - '@strands-agents/sdk'
      - '@nestjs/platform-socket.io'
      - 'ioredis'
      - 'mqtt'
      - 'class-transformer/storage'
      - 'class-transformer'
      - 'class-validator'
      - 'kafkajs'
      - 'nats'
      - '@grpc/grpc-js'
      - '@grpc/proto-loader'
      - 'amqplib'
      - 'amqp-connection-manager'

plugins:
  - serverless-step-functions
  - serverless-offline

package:
  individually: true

functions:
  wrapperAdapter:
    handler: dist/wrapper/handler.startAnalysis
    timeout: 29
    memorySize: 1024
    environment:
      STATE_MACHINE_ARN: !Sub 'arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:ms2-pipeline-${sls:stage}'
    events:
      - http:
          path: /analyze
          method: post
          cors: true

  pullRepoToS3:
    handler: dist/lambdas/pull-repo.handler
    timeout: 900
    memorySize: 8192
    ephemeralStorageSize: 8192
    environment:
      S3_BUCKET_NAME: !Ref RepositoryBucket
    layers:
      - arn:aws:lambda:eu-central-1:553035198032:layer:git-lambda2:8

  webhookSender:
    handler: dist/lambdas/webhook.handler
    environment:
      DESTINATION_API_KEY: ${ssm:/amerigo/risposta/api-key}
      DESTINATION_URL: ${ssm:/amerigo/url}
    timeout: 15

  orchestrator:
    handler: dist/lambdas/orchestrator-lambda.orchestratorHandler
    timeout: 900
    memorySize: 8192
    ephemeralStorageSize: 8192
    environment:
      LAMBDA_OWASP_NAME: ms2-analysis-service-${sls:stage}-owaspAgent
      LAMBDA_TEST_NAME: ms2-analysis-service-${sls:stage}-testAgent
      LAMBDA_DOCS_NAME: ms2-analysis-service-${sls:stage}-docsAgent
      MASTER_LEAD_AGENT_ID: 'A8A2WWKF9S'

  owaspAgent:
    handler: dist/lambdas/owasp-agent-lambda.owaspAgentHandler
    timeout: 900
    memorySize: 8192
    ephemeralStorageSize: 8192
    environment:
      OWASP_DEP_AGENT_ID: 'KUE8YYMLKK'
      OWASP_CREDS_AGENT_ID: 'QDRECNXUGR'
      OWASP_CORE_AGENT_ID: 'FJPDLGYFQM'
      OWASP_LEAD_AGENT_ID: 'PILT1S5IL6'
      TEST_QA_AGENT_ID: 'EXDHLR6GUP'
      TEST_GEN_AGENT_ID: '3IIAWFA9BC'
      TEST_AUDIT_AGENT_ID: 'BNBKYAFDME'
      TEST_AGENT_ID: 'L3EB5WS1ZU'
      DOCS_TECH_AGENT_ID: 'ZPFNNQK2FO'
      DOCS_GOV_AGENT_ID: 'UVFEQBJS1T'
      DOCS_AGENT_ID: 'DB16ZAYK3A'
      OWASP_AGENT_ALIAS_ID: TSTALIASID

  testAgent:
    handler: dist/lambdas/test-agent-lambda.testAgentHandler
    timeout: 900
    memorySize: 8192
    ephemeralStorageSize: 8192
    environment:
      TEST_QA_AGENT_ID: L3EB5WS1ZU
      TEST_GEN_AGENT_ID: L3EB5WS1ZU
      TEST_AUDIT_AGENT_ID: L3EB5WS1ZU
      TEST_AGENT_ALIAS_ID: TSTALIASID

  docsAgent:
    handler: dist/lambdas/docs-agent-lambda.docAgentHandler
    timeout: 900
    memorySize: 8192
    ephemeralStorageSize: 8192
    environment:
      DOCS_TECH_AGENT_ID: DB16ZAYK3A
      DOCS_GOV_AGENT_ID: DB16ZAYK3A
      DOCS_UX_AGENT_ID: DB16ZAYK3A
      DOCS_AGENT_ALIAS_ID: TSTALIASID

  failureHandler:
    handler: dist/lambdas/failure-handler.handler
    timeout: 20
    memorySize: 256
    environment:
      DESTINATION_URL: ${ssm:/amerigo/url}
      DESTINATION_API_KEY: ${ssm:/amerigo/risposta/api-key}

# Definizione della Step Function
stepFunctions:
  stateMachines:
    RepoAnalysisStateMachine:
      name: ms2-pipeline-${sls:stage}
      definition: ${file(state-machine.json)}

# Creazione del Bucket S3
resources:
  Resources:
    RepositoryBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ms2-analysis-repos-bucket-${sls:stage}-${aws:accountId}
        LifecycleConfiguration:
          Rules:
            - Id: AutoDeleteOldZips
              Status: Enabled
              ExpirationInDays: 1
